### ISSUE TITLE
document env vars

### ISSUE THREAD

**Issue by ahdinosaur** [prebuild/prebuildify#21]
forking from https://github.com/mafintosh/prebuildify/pull/19, :fork_and_knife: 

here is an issue to document `prebuildify`'s environment variables: :star2: 

- `ARCH`
- `PLATFORM` (proposed in #20)
- `PREBUILD_ARCH`
- `PREBUILD_PLATFORM`
- `PREBUILD_NODE_GYP`
- `STRIP` (proposed in #19)

i'm also curious about the reason for both `ARCH` and `PREBUILD_ARCH`, and whether we should commit to one or the other.

cheers! :heart:

**Comment by ralphtheninja** [comment]
It seems to me that `PREBUILD_ARCH` and `PREBUILD_PLATFORM` aren't used inside `prebuildify` and not inside `node-gyp`. I'm guessing they are meant to be passed on to `preinstall` and `postinstall` scripts?

**Comment by vweevers** [comment]
They were introduced in https://github.com/mafintosh/prebuildify/pull/12. Could you shed some light on this @jimpick?

**Comment by ralphtheninja** [comment]
> They were introduced in #12. Could you shed some light on this @jimpick?

Actually, #12 introduced `PREBUILD_PLATFORM` and `PREBUILD_NODE_GYP` but `PREBUILD_ARCH` seems to have been introduced earlier. Just fyi.

**Comment by jimpick** [comment]
You can see where I used it here:

https://github.com/jimpick/utp-native-prebuilds-nodejs-mobile/blob/master/build-ios-arm64.sh#L15

I think PREBUILD_NODE_GYP was needed with the particular cross-compiling toolchain I was using (from nodejs-mobile) to get it to use a specific node-gyp path.

It's been a while since I did it, and I didn't keep the prebuilds updated, but you can see where I used PREBUILD_PLATFORM here:

https://github.com/jimpick/sodium-native/blob/ios-prebuild/preinstall.js#L12

I never created a PR for that fork as it was targeting a rapidly evolving toolchain from nodejs-mobile, and I didn't expect the upstream sodium-native developers to have to maintain those prebuilds (or myself, for that matter).

**Comment by ralphtheninja** [comment]
@ahdinosaur As @jimpick just linked, it seems we want to use `PLATFORM` in the same way as `PREBUILD_PLATFORM` above so it makes sense to rename `PLATFORM` to `PREBUILD_PLATFORM` in https://github.com/prebuild/prebuildify/pull/20
